apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace}}
  labels:
    {{- range $key, $value := .Values.labels}}
        {{$key}}: {{$value | quote}}
    {{- end}}
  annotations:
    description: "Namespace for {{ .Values.namespace}} web application"