apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}-network-policy
  namespace: {{ .Values.namespace}}
spec:
  podSelector:
    matchLabels:
      {{- range $key, $value := .Values.labels}}
      {{$key}}: {{$value | quote}}
      {{- end}}
  policyTypes:
      {{- range $value := .Values.networkPolicy.policyTypes}}
      - {{$value}}
      {{- end}}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: allowed-app
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
