apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- range $key, $value := .Values.labels}}
        {{$key}}: {{$value | quote}}
    {{- end}}
